Coord gen code for Graph vis using Canvas
swsnu/swppfall2022-team9 pull request #2
Opened 2022-10-13 16:57 UTC by JadenJSPark

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-10-14 01:45 UTC, dongjoocha requested changes
수고 많으셨습니다.

2022-10-14 01:45 UTC, dongjoocha commented on frontend/src/components/Graph/Canvas.ts
> +export const get_2_chon_coordinates = (number_1_chon: number, numbers_2_chon: number[], radius: number, max_connections = 10, margin = 22) => {
우리가 설정한 eslint 규칙에 따라 함수명이나 변수명을 수정할 필요가 있습니다. camelCase, PascalCase, UPPER_CASE 중 하나로 작성해야 합니다.

2022-10-14 01:45 UTC, dongjoocha commented on frontend/src/components/Graph/Canvas.ts
> +    let max_2_chon = Math.min(Math.floor(budget / margin)+1, 10)
code formatter도 사용해주세요.
```ts
let max_2_chon = Math.min(Math.floor(budget / margin) + 1, 10);
```

1. vscode에서 Prettier - Code formatter 확장 설치
2. Ctrl + Shift + P -> Format Selection With... -> Prettier Code formatter
3. format 하고자 하는 파일로 이동
4. Ctrl + Shift + P -> Format Document(단축키 설정해놓으면 편함)

2022-10-14 01:45 UTC, dongjoocha commented on frontend/src/components/Graph/Canvas.ts
> +// console.log(get_2_chon_coordinates(5, [5,3,6,6,6], 3));
불필요한 주석은 삭제해주세요.

2022-10-14 03:37 UTC, notiona commented
저도 위 3가지 수정사항만 다 수정되면 merge 되는거 좋습니다~

2022-10-14 04:56 UTC, hunkim98 commented on frontend/src/components/Graph/Canvas.ts
> +export const get_2_chon_coordinates = (number_1_chon: number, numbers_2_chon: number[], radius: number, max_connections = 10, margin = 22) => {
frontend는 camelCase로 하죠

2022-10-14 05:03 UTC, hunkim98 requested changes
고생하셨습니다. 로컬에서 commit 하고 다시 review request를 보내주시면 감사하겠습니다.

2022-10-14 05:03 UTC, hunkim98 commented on frontend/src/components/Graph/Canvas.ts
> +export const get_2_chon_coordinates = (number_1_chon: number, numbers_2_chon: number[], radius: number, max_connections = 10, margin = 22) => {
number_1_chon 보다는 1ChonCount가 더 나은 변수명일 것 같습니다.

2022-10-14 05:03 UTC, hunkim98 commented on frontend/src/components/Graph/Canvas.ts
> +    let max_2_chon = Math.min(Math.floor(budget / margin)+1, 10)
추거적으로 format on save라는 옵션을 vscode상에서 설정하면, 저장할때마다 자동으로 format해줄 겁니다.

2022-10-16 08:02 UTC, hunkim98 commented on frontend/src/components/Graph/Canvas.ts
> +const degToRad = (degrees: number) => {
근데 생각해보니깐 저희 테스트코드도 짜긴 해야해서 Canvas.ts에 다 넣어도 될 것 같습니다

2022-10-17 04:47 UTC, JadenJSPark commented on frontend/src/components/Graph/Canvas.ts
> +export const get_2_chon_coordinates = (number_1_chon: number, numbers_2_chon: number[], radius: number, max_connections = 10, margin = 22) => {
변수명이 숫자로 시작하는게 안돼서요. `oneChonCount`로 바꿀게요.

2022-10-17 05:16 UTC, notiona approved these changes

2022-10-17 05:17 UTC, hunkim98 approved these changes
잘 정리된 것 같습니다. 고생하셨습니다

2022-10-17 06:02 UTC, dongjoocha approved these changes

2022-10-17 06:13 UTC, merged