Implement gmail smtp email test
swsnu/swppfall2022-team9 pull request #35
Opened 2022-11-01 08:13 UTC by hunkim98

Implemented gmail smtp email sending functions

You can test it out by calling a GET to 'http://127.0.0.1:8000/api/test-email/'!

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-11-01 14:50 UTC, notiona requested changes

2022-11-01 14:50 UTC, notiona commented on backend/backend/settings.py
> +EMAIL_HOST_PASSWORD = 'svbxriqrzdrzshsx'
Public repo에 host password를 넣는 것은 좋은 생각이 아닌것 같습니다.

2022-11-01 14:51 UTC, hunkim98 commented on backend/backend/settings.py
> +EMAIL_HOST_PASSWORD = 'svbxriqrzdrzshsx'
네넵 임시로 일단 settings.py에 넣었는데, .env파일로 옮길까요?

2022-11-02 06:47 UTC, notiona commented on backend/backend/settings.py
> +EMAIL_HOST_PASSWORD = 'svbxriqrzdrzshsx'
그래서 settings.py에 SECRET_KEY도 일단 .env 파일에 넣긴 했는데, 그러면 그것도 차라리 소스코드에 넣는 게 어떻까 싶네요. env가 없는 상태에서 sonarcloud에서도 에러나 가서 travis CI 설정에 SECRET_KEY를 넣어주긴 했습니다. 그 방식이라면 EMAIL_HOST_PASSWORD도 처리할 수 있을 것 같네요

2022-11-02 07:25 UTC, notiona commented on backend/backend/settings.py
> +EMAIL_HOST_PASSWORD = 'svbxriqrzdrzshsx'
일단은 production 단계가 아니니까 env 파일에 secret 정보를 담아두고 그걸 코드로 불러오는 로직은 넣되, .env파일을 공개해서 git clone 받았을 때 바로 실행할 수 있도록 하죠! 나중에 secret value를 진짜 숨겨야 하는 값으로 바꾸면 그때 .env를 gitignore 하면 될 것 같아요.

2022-11-02 07:25 UTC, notiona approved these changes

2022-11-02 07:29 UTC, notiona commented
LGTM

2022-11-02 07:30 UTC, merged