SignUp Page and co
swsnu/swppfall2022-team9 pull request #5
Opened 2022-10-26 11:12 UTC by dongjoocha

## Description
- Implement SignUpPage(`/user/signup`)
- Implement common form style

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/74580163/198010624-0e25fb98-6f21-42cb-9fdd-5c8189dbea55.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-10-26 15:12 UTC, hunkim98 requested changes
고생하셨습니다. React component안에 isFormValid와 같이 변하는 변수는 useState를 사용해서 관리하는 게 안전합니다!

2022-10-26 15:12 UTC, hunkim98 commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  let isFormValid = false;
isFormValid는 useState로 변경해서 사용하는 게 좋을 것 같습니다

2022-10-26 15:12 UTC, hunkim98 commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  const [signUpHelper, setSignUpHelper] = useState<SignUpInfo>({
Signup helper를 없애도 될 것 같습니다. signup helper 없이 JSX.Element안에 inline하는 방식으로 하면 좋을 것 같습니다.

ex) {(isFormValid && !signUpInfo.name) && <S.InputHelper>{signUpHelper.nickname}</S.InputHelper>}

2022-10-26 15:12 UTC, hunkim98 commented on frontend/src/styles/common.form.styles.ts
> +export const CloseButtonContainer = styled.div`
form은 close button이 필요 없을 것 같습니다.

2022-10-26 15:12 UTC, hunkim98 commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  useEffect(() => {
여기 useEffect는 없애는 방식으로 짜면 좋을 것 같습니다.

onSubmit할 때 모든 에러를 찾고 그에 따라 helper text가 보이게 하면 될 것 같습니다

2022-10-26 15:12 UTC, hunkim98 commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +                autoComplete="on"
닉네임은 autoComplete할 필요는 없을 것 같습니다.

2022-10-26 15:16 UTC, dongjoocha commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  const [signUpHelper, setSignUpHelper] = useState<SignUpInfo>({
useState로 쓰지 말고 enum으로 선언해서 사용하라는 말씀이시죠?

2022-10-26 15:17 UTC, dongjoocha commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  useEffect(() => {
원래 그렇게 하려고 했는데 에러 체크 시 state인 `signUpHelper`를 써서 동기 처리가 안 되더라구요... enum으로 바꿔서 다시 해볼게요.

2022-10-26 15:20 UTC, hunkim98 commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  const [signUpHelper, setSignUpHelper] = useState<SignUpInfo>({
네넵~ useState는 react componenet 안에서 유저의 특정 행동이나 event에 따라 변하는 변수가 있을 때 사용합니다. input helper를 usestate를 사용해서 구현해도 상관없지만, 지금 구현한 것을 보면 "" 이든지 enum값인 것으로 보아 useState까지 필요한 것 같지 않습니다.

2022-10-26 15:27 UTC, hunkim98 commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  useEffect(() => {
onSubmit할 시 에러가 뜨게 하려면 useState를 쓸 수 밖에 없을 것 같다고 생각합니다. useState를 사용하실 생각이면 enum에 NO_ERROR도 추가하는 방법도 고려하면 좋겠어요. (NO_ERROR = "") 

 const [signUpHelper, setSignUpHelper] = useState<SignUpInfo>({
    name: HelperText.NO_ERROR,
    email:  HelperText.NO_ERROR,
    nickname: HelperText.NO_ERROR,
    password: HelperText.NO_ERROR,
    passwordConfirm:  HelperText.NO_ERROR,
  });

그렇게 하고 나서 <S.InputHelper>{signUpError.password}</S.InputHelper> 이런식으로 하면 될 것 같습니다!

2022-10-26 15:35 UTC, dongjoocha commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  useEffect(() => {
네 역시 useState 쓰는 수밖에 없겠네요 ㅜ

2022-10-27 07:11 UTC, hunkim98 approved these changes
Much better😇

이 브랜치 merge하면 이후 feature/panZoom 브랜치를 merge할 때 frontend lint 전체 확인해보겠습니다.

2022-10-27 13:38 UTC, notiona approved these changes

2022-10-27 13:38 UTC, merged