Backend/friend request APIs
swsnu/swppfall2022-team9 pull request #82
Opened 2022-11-22 14:28 UTC by notiona

## Description

This PR implements major backend FriendRequest related APIs.

+ GET /api/friendRequest/
+ GET /api/friendRequest?user1Id=${user1Id}&user2Id=${user2Id}/
+ POST /api/friendRequest/
+ PUT /api/friendRequest/:friendRequestId/
For PUT /api/friendRequest/:friendRequestId/, a state transition table is used to classify each state transition.
![image](https://user-images.githubusercontent.com/37995888/203340552-8543b455-0a6f-4a4d-ac34-38d593af2d73.png)

Also this PR implements two major invariants of LinkLink.
+ For any two users, there can only exist one FriendRequest
+ For any user, a user can only maintain less than or equal to MAX_ONECHON(10) onechons.

Please refer to the Notion REST API docs for more detailed information.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-11-22 15:03 UTC, hunkim98 requested changes
눈물나는 코드입니다. 고생하셨습니다.

2022-11-22 18:18 UTC, notiona commented on backend/linklink/models.py
> +        self.unique_request_id = "-".join([
LinkLink 앱의 invariant 중 하나인 "임의의 두 유저 사이에는 오직 하나의 FriendRequest만이 존재할 수 있다"라는 invariant를 구현하기 위한 장치입니다. FriendRequest에 unique_request_id라는 field를 만들고, 이것을 `user1_id->user2_id`의 형태로 만들어 저장합니다. 이때, FriendRequest의 유일성을 위해 `user1_id`는 sender가 아니라 두 유저 중 `user_id`가 더 작은 쪽, `user2_id`는 두 유저 중 `user_id`가 더 큰 쪽으로 정렬해 생성하고, 이 field는 `editable=False`로 만듦으로써 Django의 Integrity Check를 직접적으로 활용할 수 있게 됩니다.

2022-11-22 18:18 UTC, notiona commented on backend/linklink/models.py
> +    unique_request_id = models.CharField(
LinkLink 앱의 invariant 중 하나인 "임의의 두 유저 사이에는 오직 하나의 FriendRequest만이 존재할 수 있다"라는 invariant를 구현하기 위한 장치입니다. FriendRequest에 unique_request_id라는 field를 만들고, 이것을 `user1_id->user2_id`의 형태로 만들어 저장합니다. 이때, FriendRequest의 유일성을 위해 `user1_id`는 sender가 아니라 두 유저 중 `user_id`가 더 작은 쪽, `user2_id`는 두 유저 중 `user_id`가 더 큰 쪽으로 정렬해 생성하고, 이 field는 `editable=False`로 만듦으로써 Django의 Integrity Check를 직접적으로 활용할 수 있게 됩니다.

2022-11-22 18:19 UTC, notiona commented on backend/linklink/models.py
> +    unique_request_id = models.CharField(
Max onechon invariant는 직접 코드로 구현해 확인해야 하지만, FriendRequest 유일성의 경우 위와 같은 방법으로 더 안전한 django의 integrity check를 그대로 활용하는 방식으로 구현했습니다.

2022-11-22 18:21 UTC, notiona commented on backend/linklink/views.py
> +            for pending_friend_request in pending_friend_requests:
가능합니다. 혹시 `GET /api/friendRequest?user1Id=${user1Id}&user2Id=${user2Id}/`에도 senderImgUrl과 senderName field가 필요한가요?

2022-11-22 18:42 UTC, notiona commented on backend/linklink/views.py
> +            for pending_friend_request in pending_friend_requests:
아래 커밋 [80a9bb5](https://github.com/swsnu/swppfall2022-team9/pull/82/commits/80a9bb5bed19a92a6408e579583567e22347a98d)에 `GET /api/friendRequest?user1Id=${user1Id}&user2Id=${user2Id}/`에는 두 field를 response body에 추가했습니다.

2022-11-23 03:46 UTC, hunkim98 commented on backend/linklink/views.py
> +            for pending_friend_request in pending_friend_requests:
`GET /api/friendRequest?user1Id=${user1Id}&user2Id=${user2Id}/` 도 일단 senderImgUrl과 senderName field를 추가해주시면 감사하겠습니다

2022-11-23 03:48 UTC, hunkim98 approved these changes
`GET /api/friendRequest?user1Id=${user1Id}&user2Id=${user2Id}/` response에도 field 두개(senderImgUrl, senderName)를 추가하면 바로 merge해도 될 것 같습니다.

2022-11-23 05:38 UTC, notiona commented on backend/linklink/views.py
> +            for pending_friend_request in pending_friend_requests:
`GET /api/friendRequest?user1Id=${user1Id}&user2Id=${user2Id}/`에도 두 field를 response body에 추가했습니다.

2022-11-23 10:36 UTC, merged